### ISSUE TITLE
Dubbing API access 

### ISSUE THREAD

**Issue by cbonnett** [elevenlabs/elevenlabs-python#130]
Would love to get dubbing API access. 
It would also be great it we could choose from the voice library to choose the voice for the translation. 
The clones voice doesn't work well for translation as the accent tends to come through very strong.

**Comment by silverbulletmdc** [comment]
+1

**Comment by xpfoxs** [comment]
+1

**Comment by harmindersinghnijjar** [comment]
I agree with this sentiment.

**Comment by UltimateKingW** [comment]
> Would love to get dubbing API access. It would also be great it we could choose from the voice library to choose the voice for the translation. The clones voice doesn't work well for translation as the accent tends to come through very strong.

I looked on RapidAPI, there's an audio dubbing API using elevenlabs: [elevenlabs dubbing](https://rapidapi.com/Thomcle/api/elevenlabs-dubbing1) I've dubbed some of my videos with the API and it works pretty well.

**Comment by code-runner-2017** [comment]
It looks like an unofficial API. Would this be a violation of Elevenlabs T&C or it is perfectly legal? Do you know if this API can be used for testing only, and not commercial usage?

**Comment by UltimateKingW** [comment]
> It looks like an unofficial API. Would this be a violation of Elevenlabs T&C or it is perfectly legal? Do you know if this API can be used for testing only, and not commercial usage?

I've integrated the API into one of my applications, there's nothing illegal about it according to the developer because it's simply an architechture that uses the elevenlabs API, it's in no way stealing from the dubbing tool available on the elevenlabs site I think. It's a free tool up to a certain point (every month you get free requests) but otherwise it's a very inexpensive tool compared to the alternatives.

**Comment by sidneyvanness** [comment]
Agree with this sentiment for sure. Surprised there isn't already an endpoint for it. Any timeframe for this?

**Comment by iotgopher** [comment]
when will dubbing be available via API? 
super important feature, right now blocking for us

**Comment by sidneyvanness** [comment]
> > It looks like an unofficial API. Would this be a violation of Elevenlabs T&C or it is perfectly legal? Do you know if this API can be used for testing only, and not commercial usage?
> 
> I've integrated the API into one of my applications, there's nothing illegal about it according to the developer because it's simply an architechture that uses the elevenlabs API, it's in no way stealing from the dubbing tool available on the elevenlabs site I think. It's a free tool up to a certain point (every month you get free requests) but otherwise it's a very inexpensive tool compared to the alternatives.

@UltimateKingW any chance you have time to chat about this? I'd be happy to give them my money for this API at a fair price, but until they do, I'd like to implement a workaround. Would be interested in picking your brain on this, and how it has worked for you in the real world.

**Comment by marius-bardan** [comment]
thanks for the update.
I can't see how can one choose a voice model for it. as initially stated, the auto-dubbing's accents are too strong.
also, are there any plans on providing a /streaming API for this?

**Comment by mvoodarla** [comment]
I was looking at [the reference](https://elevenlabs.io/docs/api-reference/create-dub#openapi-post-v1dubbing) and it seems like we have to specify transcripts, speakers, background, audio, etc. in order to use the API. To that end, we ended up building a version of dubbing that uses ElevenLabs API as a backend for just the text to speech portion.

You can check it out here: https://www.sievedata.com/functions/sieve/dubbing

Hope it's useful to the community!
