### ISSUE TITLE
Is it possible to specify a language when using the API?

### ISSUE THREAD

**Issue by redwoodzero0** [elevenlabs/elevenlabs-python#149]
I am using ElevenLabs using the API, but how can I set the voice language? I don't have a problem when I output in English, but when I use other languages, it reads the sentence with English pronunciation if the sentence is long. Is it possible to specify the language of the voice to output in a specific language? I want to output in korean.
I attach below the code I am using.

```
import time
from elevenlabs import generate, play, set_api_key, VoiceSettings, Voice, requests

KEY = "key"
VoiceID = "id"
VoiceName = "name"

time = time.strftime("%m%d%H%M%S", time.localtime(time.time()))

url = "https://api.elevenlabs.io/v1/text-to-speech/{VoiceID}"

set_api_key(f"{KEY}"),
settings=Voice(
    voice_id=f'{VoiceID}',
    name=f'{VoiceName}',
    settings=VoiceSettings(stability=0.5, similarity_boost=0.5, style=0.09)
),

audio = generate(
  text= "Text",
  voice= f"{VoiceName}",
  model= "eleven_multilingual_v2"
)

play(audio, notebook=True)
```

**Comment by mamamiawhatacode** [comment]
Same

**Comment by Brasidas1974** [comment]
Likewise

**Comment by droolingOnU88** [comment]
Likewise

**Comment by ramyzeidan** [comment]
anyone got this fixed or found a way around?

**Comment by verybigelephants** [comment]
+1 This is super annoying for slavic languages that are similar. ElevenLabs sometimes determines the language wrong because of similar words (slovak/czech/serbian/...) and then the pronounciation is all messed up

The only workaround is to provide a longer non-related text with words specific to the relevant language only, but then the api is non-usable, as you don't know where you should cut it automaticlly

Also, what's worse, since ElevenLabs processes input in batches it sometimes even generates first half of the output in one languge and then switches to other because it thinks that it's something else and has no context of previous genertion batch 

I understand that this issue related to api itself, not the python implementation, but there's no official channel for eleven labs api itself

**Comment by Jitendra2603** [comment]
https://help.elevenlabs.io/hc/en-us/articles/19581255545873-How-do-I-select-the-language-and-accent-

**Comment by dsinghvi** [comment]
Closing this issue since this is not a Python SDK issue and a general API request for the ElevenLabs team.

**Comment by Nasnl** [comment]
I think it's still not fixed....

**Comment by Jitendra2603** [comment]
https://elevenlabs.io/docs/api-reference/text-to-speech/convert

language_code
string
Optional
Language code (ISO 639-1) used to enforce a language for the model. Currently only Turbo v2.5 and Flash v2.5 support language enforcement. For other models, an error will be returned if language code is provided.
