### ISSUE TITLE
Type error in `FineTuningResponse` causing Voice serialization to fail

### ISSUE THREAD

**Issue by mbforbes** [elevenlabs/elevenlabs-python#324]
`Voice.fine_tuning.message` is typed as an optional `str`:
https://github.com/elevenlabs/elevenlabs-python/blob/7af17bce7abcfa5e761ab02813ed592ab581da1c/src/elevenlabs/types/fine_tuning_response.py#L22

... but what's given back from the API is actually an object. For example, Freya:
```json5
  "Freya": {
    "voice_id": "jsCqWAovK2LkecY7zXl4",
    ...
    "fine_tuning": {
     ...
      "message": {
        "eleven_multilingual_v2": "",
        "eleven_turbo_v2": "",
        "eleven_turbo_v2_5": ""
      },
      ...
    },
    ...
}
```

 
This manifests an error if I try to serialize the Voice (to JSON) and then load it with `Voice.validate()`:

```
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Voice                                                                 
fine_tuning -> message                                                                                                                   
  str type expected (type=type_error.str)  
```

**Comment by dsinghvi** [comment]
@mbforbes this turned out to be a break in the eleven labs api, and is fixed in the [latest SDK version](https://github.com/elevenlabs/elevenlabs-python/blob/0da9d77b28417b80219ef20b094dc81953cb9385/src/elevenlabs/types/fine_tuning_response.py#L22)! 

You should be able to download version [v1.6.0rc0](https://github.com/elevenlabs/elevenlabs-python/releases/tag/v1.6.0rc0) for the fix.

**Comment by mbforbes** [comment]
Thanks for the quick turnaround on this!
