### ISSUE TITLE
I am getting a value error

### ISSUE THREAD

**Issue by Eric-Denny** [elevenlabs/elevenlabs-python#50]
raise ValueError("ffplay from ffmpeg not found, necessary to play audio.")
ValueError: ffplay from ffmpeg not found, necessary to play audio.

##this is the output i recieve when i run this code.

""from elevenlabs import generate, play
audio = generate(
  text="Hi! My name is Bella, nice to meet you!",
  voice="Bella",
  model="eleven_monolingual_v1"
)

play(audio)""

**Comment by flavioschneider** [comment]
As the error says, you need to install ffmpeg to play audio.

**Comment by alainbuyze** [comment]
hello, I have the same error. Running windows10 and **ffmpeg is installed** through 'pip install ffmpeg '. Do I need to install something else, as the message says that it does not find ffplay.  BTW, I can run the above example without any problems from the example in the github website.

**Comment by RJsam3** [comment]
I think some clarification might be needed. When it says ffplay, is that talking about the media player using the FFmpeg libraries and the SDL library, or a function from a package called ffmpeg? 
If the former, saying it's required in the readme would probably help.

**Comment by rohingosling** [comment]
I get the same error. I also have ffmpeg installed, same as @alainbuyze, "pip install ffmpeg".

But I still get the "ffplay from ffmpeg not found" error.

Here is the full traceback I'm getting.

'
Traceback (most recent call last):
  File "X:\Projects\common_python\application\talk_gpt\elevenlabs_test.py", line 9, in <module>
    play ( audio )
  File "C:\Users\...\anaconda3\lib\site-packages\elevenlabs\utils.py", line 24, in play
    raise ValueError("ffplay from ffmpeg not found, necessary to play audio.")
ValueError: ffplay from ffmpeg not found, necessary to play audio.
`

**Comment by rohingosling** [comment]
Yup, I found this code. They appear to be calling ffplay from the command line, with arguments -autoexit to exit after playing a video, and -nodisp to disable the graphical display. 

`def play(audio: bytes, notebook: bool = False) -> None:
    if notebook:
        from IPython.display import Audio, display

        display(Audio(audio, rate=44100, autoplay=True))
    else:
        if not is_installed("ffplay"):
            raise ValueError("ffplay from ffmpeg not found, necessary to play audio.")
        args = ["ffplay", "-autoexit", "-", "-nodisp"]
        proc = subprocess.Popen(
            args=args,
            stdout=subprocess.PIPE,
            stdin=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        out, err = proc.communicate(input=audio)
        proc.poll()`

**Comment by rohingosling** [comment]
So, I got it to work. Here are the steps I followed.

**Step 1: Download the ffmpeg suite of command line tools.** 

- There are no installers for this, and the ffmpeg project only make their source code available. 
- But, they do have links to external projects that do regular automated builds, which you can find on the download page, https://ffmpeg.org/download.html#build-windows.
- I downloaded the latest "shared" build from BtbN, https://github.com/BtbN/FFmpeg-Builds/releases.
- I don't think Elevenlabs require the shared build, which just includes libraries for integration and stuff. ElevenLabs seem to just be using ffplay directly from the command line. But, just in case, I downloaded the shared version.

**Step 2: Unzip the ffmpeg archive and copy the root folder to there ever you want to store it.**

- In my case I just coppied it to "C:\Program Files (x86)", and changed the folder name to "ffmpeg" just to make the path a bit shorter for the sake of convenience. So my Win64 Windows programs path looks like this.
C:\Program Files (x86)\ffmpeg\
    bin
    doc
    include
    lib
    LICENSE.txt
- I presume if you download the "non-shared" build, then you won't have the include and lib folders. But, as mentioned above, I just downloaded the shared build just in case it's needed. 

**Step 3: Add the ffmpeg "bin" folder to the system path.**

- In my case, I added "C:\Program Files (x86)\ffmpeg\bin" to the system path, using the Windows environment variables editor.

**Step 4: Test**

- To confirm that the ppmpeg bin folder has been added to the system path correctly, I opened up a console and checked to see if I could execute ppplay.exe. 
- Then I tried out some code. I used the example below. And, it worked. 
...python
from elevenlabs import generate, play

audio = generate (
    text  = "Hello World!.\nTesting 1, 2, 3.\nYo, wuzuuuuuuuuup!",
    voice = "Bella",
    model = "eleven_monolingual_v1"
)

play ( audio )
...

**Comment by rohingosling** [comment]
I was just thinking, just an idea, to the ElevenLabs dev team.

I'm sure there is a good reason why ffplay is being used here. However, ppmpeg is more for playing and processing videos from the command line, rather than than playing audio programatically from python. Just as an idea, would it not not be more convenient to use a python library, like pygame or simpleaudio, or something like that?

**Comment by RJsam3** [comment]
I looked through the code and found the same thing. That's why I brought it up. 

I installed it (the actual software, not the python module), and its already proven useful, so I can't say I mind it. However, even after adding it to the system path, it did not work for me (the elevenlabs package). I'm sure it's an issue on my side, but by that point I was done with it and just switched to the unofficial version, which does NOT require ffplay. or ffmpeg to play audio.

I'm going to bring this up one more time, it would be really great if someone could add a little notice to the readme somewhere that this package requires ffmpeg and ffplay (how to install it would be good too, for people who have never heard of it but most people could probably figure it out on their own), and perhaps change the error message to specify it means the software and NOT the python package.

**Comment by rohingosling** [comment]
> ...and perhaps change the error message to specify it means the software and NOT the python package.

That is actually a good idea. Because the current error message makes it look like a missing package. But it's actually a literal exe that needs to be run.

One thing ElevenLabs can do, is just use a python packages that plays audio though. I haven't looked at the code, but I have a hunch the unofficial version has just replaced command line calls to ffplay.exe, with calls to a Python package like pygame or simpleaudio, etc. Not sure why ElevenLabs when with this ffplay option. Especially since it's a video player, and we only interested in audio in this case. I'm sure they have a good reason for using ffplay. But, just an odd option to go with, if you looking at it from the outside in.

**Comment by flavioschneider** [comment]
Hi all, we decided to use ffmpeg as audio player because it's a common tool for audio processing and doesn't add any extra dependency. Here's an alternative `play` function that uses existing python packages (`pip install soundfile sounddevice`) if ffmpeg doesn't work for you.

```py
import io
import soundfile as sf
import sounddevice as sd
from elevenlabs import generate

audio = generate(
    text="Hi! My name is Bella, nice to meet you!",
    voice="Bella",
    model="eleven_monolingual_v1"
)

def play(audio: bytes):
    sd.play(*sf.read(io.BytesIO(audio)))
    sd.wait()

play(audio)
```
